{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "canary-demo.ingressName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "canary-demo.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.className "alb" }}
    # AWS Load Balancer Controller annotations
    kubernetes.io/ingress.class: alb
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.aws.vpc.subnets }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.aws.vpc.subnets }}
    {{- end }}
    {{- if .Values.aws.certificate.arn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.aws.certificate.arn }}
    {{- end }}
    {{- if and .Values.aws.waf.enabled .Values.aws.waf.arn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.aws.waf.arn }}
    {{- end }}
    {{- else }}
    # NGINX Ingress Controller annotations
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- if .Values.externalDns.enabled }}
    # External DNS annotations
    {{- with .Values.externalDns.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "canary-demo.rootServiceName" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
