apiVersion: v1
kind: Service
metadata:
  name: canary-demo-stable
  namespace: default
  labels:
    app: canary-demo
    service-type: stable
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-demo

---
apiVersion: v1
kind: Service
metadata:
  name: canary-demo-canary
  namespace: default
  labels:
    app: canary-demo
    service-type: canary
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-demo

---
apiVersion: v1
kind: Service
metadata:
  name: canary-demo-root
  namespace: default
  labels:
    app: canary-demo
    service-type: root
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-demo
